language: node_js
node_js:
 - "node"
services:
  - docker
before_script:
  - cd $TRAVIS_BUILD_DIR
script:
  - yarn lint
  - docker-compose -f docker/docker-compose.yml up -d
  - yarn wait-for-docker
  - yarn test
