FROM ubuntu:18.04
MAINTAINER Martijn Jacobs <martijn@devopsconsulting.nl>

ENV REFRESHED_ON "23 Jul 2018"
ENV DEBIAN_FRONTEND noninteractive

# add saltstack key and install gnupg2
RUN apt-get update && apt-get install curl --yes && apt-get install gnupg2 --yes
RUN curl --fail --silent --show-error --location https://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
RUN echo 'deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main' > /etc/apt/sources.list.d/saltstack.list

# install salt-minion
RUN apt-get update && apt-get install salt-minion --yes

# copy the minion configuration
ADD ./conf/minion /etc/salt/minion

# show which versions are installed
RUN dpkg -l | grep salt\-
